include:
    # Left Split With Dongle Firmware
  - board: nice_nano
    shield: scylla_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: left_split_dongle

    # Right Split With Dongle Firmware
  - board: nice_nano
    shield: scylla_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: right_split_dongle

    # Dongle Central Firmware 
  - board: xiao_ble
    shield: scylla_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: dongle_central

    # Left Split With Bluetooth
  - board: nice_nano
    shield: scylla_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT=y
    artifact-name: left_split_bluetooth
    
    # Right Split With Bluetooth
  - board: nice_nano
    shield: scylla_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y
    artifact-name: right_split_bluetooth

    # Reset both splits with this firmware before flashing.
  - board: nice_nano
    shield: settings_reset
    artifact-name: keyboard_reset

    # Reset the dongle with this firmware before flashing.
  - board: xiao_ble
    shield: settings_reset
    artifact-name: dongle_reset
